### ISSUE TITLE
nanoe/Econavi support

### ISSUE THREAD

**Issue by didierm** [lostfields/python-panasonic-comfort-cloud#1]
Hi, thanks for your work.

The Panasonic Etherea models (e.g. CS-Z35TKEW : https://www.aircon.panasonic.eu/IE_en/specs/22812/229615/49/) offer Econavi (presence sensor) and nanoe (air purifier).

Any chance of supporting these features in the app ?

**Comment by lostfields** [comment]
Hi
It should be possible, all of the possible modes is set as a numeric value - we just need to know the value of each mode.

Have you tried this module? I'm wondering since it's not finished. I was thinking of uploading it to PyPi but haven't got there yet. If it's working you could run the `dump #` command to see all the data. After each dump, look at your remote to map states to the values. 

Lets say you turn Econavi on, dump the data, then turn Econavi off, dump the data and keep on for each "unknown" parameter.

**Comment by didierm** [comment]
I was already thinking in that direction, thanks for confirming.

Time permitting, I'll have a go at it next weekend.

_(getting this to work would be super duper great, as the ComfortCloud app itself has GUI provisions for e.g. nanoe, but does not support it yet)._

**Comment by lostfields** [comment]
Mine reports it doesn't have Nanoe support when it still has it, but there is another flag that is called `actualNanoe`. I'm guessing that `nanoe/actualNanoe = 1` is off and `2` is on. I'm not sure how we are going to handle the property `nanoe` vs `actualNanoe`

**Comment by lostfields** [comment]
regarding previous support where command `list` didn't work, I noticed that `actualNanoe` was zero. It looks like mine is 1 when it's off, and 2 when it's on. So I'm wondering if your units actually supports nanoe?

**Comment by didierm** [comment]
My 4 units are all the "Etherea" model (CS-Z35TKEW, see https://github.com/lostfields/python-panasonic-comfort-cloud/issues/1#issue-387041953), and support both nanoe and Econavi.

**Comment by lostfields** [comment]
looks like `ecoNavi = 1` is off when it's supported, and `ecoNavi = 0` is off for unsupported. The same value is for my nanoe, where I got the same values for `actualNanoe`. 

You `nanoe` doesn't change, but ecoNavi does. Kind of strange, but I can expose `ecoNavi` and `actualNanoe`.

**Comment by lostfields** [comment]
I'm going to treat ecoNavi and Nanoe as the same thing, or do you think that is a problem?

**Comment by inforsgit** [comment]
I reckon they should still be separate because they're different functions on the device (I think - mine only supports NanoE) - the nanoe is the air purification and the econavi is the motion detection.

Thanks as always for your amazing work on this!!

**Comment by lostfields** [comment]
After playing around with this after getting PR #23 I tried this for my unit, and I noticed that the app itself had a parameter in device list to enable Nanoe. Before I had this enabled I got this when I had deactivated nanoe with my remote.

```
iAutoX                   : False
nanoe                    : False
ecoNavi                  : False
parameters
    ecoMode              : 0
    ecoNavi              : 0
    nanoe                : 1
    actualNanoe          : 1
```

After enabling nanoe capability in device settings

```
iAutoX                   : False
nanoe                    : True
ecoNavi                  : False
parameters
    ecoMode              : 0
    ecoNavi              : 0
    nanoe                : 1
    actualNanoe          : 1
```

After setting nanoe to On in App

```
iAutoX                   : False
nanoe                    : True
ecoNavi                  : False
parameters
    ecoMode              : 0
    ecoNavi              : 0
    nanoe                : 2
    actualNanoe          : 2
```

**Comment by krueckhans** [comment]
Are u sure that ecoNavi paramter has only three possible values 0:not supported ; 1:isOff ; 2isOn?
Could it be possible that there are more values e.g. 5:TwoActivePersonsInRoomAndNoDirectSunLight. 
I am looking for a way to read the inside paramaters of the econavi feature.
If there is a possibility to get "theActivePersonsinRoom", u you could use your air con as alarm system.
