### ISSUE TITLE
Fix for CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by LudovicRousseau** [lostfields/python-panasonic-comfort-cloud#12]
I think I know why the certificate verification fails. See also https://github.com/lostfields/python-panasonic-comfort-cloud/issues/3

First test with https://www.panasonic.com/ that has no problem.
```
$ openssl s_client -connect www.panasonic.com:443
CONNECTED(00000005)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = GeoTrust RSA CA 2018
verify return:1
depth=0 C = JP, ST = Osaka, L = Kadoma City, O = Panasonic Corporation, CN = *.panasonic.com
verify return:1
---
Certificate chain
 0 s:/C=JP/ST=Osaka/L=Kadoma City/O=Panasonic Corporation/CN=*.panasonic.com
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=GeoTrust RSA CA 2018
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=GeoTrust RSA CA 2018
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
---
[...]
```

Second test with https://accsmart.panasonic.com/
```
± openssl s_client -connect accsmart.panasonic.com:443
CONNECTED(00000006)
depth=0 C = JP, ST = Osaka, L = Kadoma City, O = Panasonic Corporation, CN = accsmart.panasonic.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = JP, ST = Osaka, L = Kadoma City, O = Panasonic Corporation, CN = accsmart.panasonic.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/C=JP/ST=Osaka/L=Kadoma City/O=Panasonic Corporation/CN=accsmart.panasonic.com
   i:/C=JP/O=Cybertrust Japan Co., Ltd./CN=Cybertrust Japan Public CA G3
---
[...]
```

One difference is the certification chain.
For accsmart.panasonic.com the server indicates "Cybertrust Japan Public CA G3" as the root CA.
But this is NOT the real root CA. The root CA is "Baltimore CyberTrust Root" but this is not reported by the server. So the intermediate certificate is missing.

I can make the http requests to work using: `requests.get("https://accsmart.panasonic.com/",   verify="CertificateChain.txt")` with `CertificateChain.txt` containing the certificate chain (attached)
[CertificateChain.txt](https://github.com/lostfields/python-panasonic-comfort-cloud/files/3490178/CertificateChain.txt)

I doubt Panasonic would ever fix their server.

I am not sure how you want to implement the fix. I propose to provide `CertificateChain.txt` and make the program use it by default. The `--skipVerify` argument would then become useless.

**Comment by lostfields** [comment]
sounds great, is it possible to supply verify with a bytearray/stream?

**Comment by LudovicRousseau** [comment]
It looks not. Only a boolean value or a file name is accepted.
https://github.com/psf/requests/blob/master/requests/adapters.py#L226

The root CA (Baltimore CyberTrust Root) is also present in `certifi/cacert.pem` https://github.com/certifi/python-certifi/blob/master/certifi/cacert.pem#L126 used by requests to check the TLS certificate.

Firefox and Safari has no problem checking the certificate for https://accsmart.panasonic.com/ so maybe requests can be modified to recursively get the certificate or something like that.
