### ISSUE TITLE
Support for getting the power consumption 

### ISSUE THREAD

**Issue by donnib** [lostfields/python-panasonic-comfort-cloud#17]
Hi,
Both my units have power consumption graphs, have you considered adding that functionality ?

/donnib

**Comment by LudovicRousseau** [comment]
It is already available in the historical data.
See https://github.com/lostfields/python-panasonic-comfort-cloud/commit/2eeef97e951e46e43cf669113991de7b4b410b24

**Comment by donnib** [comment]
@LudovicRousseau cool thx. i didn't notice that ;)
