### ISSUE TITLE
No more historical data

### ISSUE THREAD

**Issue by LudovicRousseau** [lostfields/python-panasonic-comfort-cloud#18]
Since a few month I have no more any historical data.
The problem is not with python-panasonic-comfort-cloud because I have the problem also with the "Comfort Cloud" iOS application.
The immediate value for internal temperature is still available using python-panasonic-comfort-cloud but not the historical values.

Maybe Panasonic does not store any history if the air conditioning system is OFF for a long time?
I last used my cooling system the 1st September 2019. I have no data for internal temperature since 20th October 2019.
The problem is that the power consumption is only available as an historical value. So I don't have the power consumption for a long period of non-use.

It is the case for other people?
Any suggestion to fix that?

**Comment by LudovicRousseau** [comment]
Surprisingly I have historic data again from 8 Jan 2020 18h00 without any change on my side. Very strange.
I then tried to use the iOS application and I had to accept again the "confidentiality policy".

**Comment by lostfields** [comment]
Suddenly got data for the first time since may 2019 at exactly 8 january too :-P

**Comment by lostfields** [comment]
closing this since we are getting data now
