### ISSUE TITLE
Summerhouse mode support

### ISSUE THREAD

**Issue by donnib** [lostfields/python-panasonic-comfort-cloud#19]
Hi,
Both units i have have one more mode along Heat, Dry, Fan etc. It's called +5 - 15C Heat which is a mode that you can use in a summerhouse and you can go as low as +5C mode. Is there a way to enable this ?

/donnib

**Comment by lostfields** [comment]
it's certainly possible, but we have to find out what value we should write. If you first set you unit to `Heat` and dump your configurations using command line, and then set your unit to `+5-15C` and dump your settings again you will probably notice a different set of data.

you may post this here and I can probably add it

**Comment by donnib** [comment]
I tried to dump but the command line tool doesn't work. i tried `python pcomfortcloud.py myuser mypass dump device 1` but i just get an error `dump: error: argument device: invalid int value: 'device'`

**Comment by lostfields** [comment]
is `python pcomfortcloud.py myuser mypass dump 1` working?

**Comment by donnib** [comment]
Ohh silly me, i misunderstood the documentation

**Comment by donnib** [comment]
Yes it works and i found out it's supported already. If you set the temperature lower than 16C it changes into this mode but as far as i can see it's not reflected in the settings, the operation mode is still3

**Comment by lostfields** [comment]
hmm, strange, what if you set it to this mode, does it adjust the temperature in the dump?

**Comment by donnib** [comment]
![image](https://user-images.githubusercontent.com/252702/72807309-6b67af80-3c57-11ea-83ac-bf060962f116.png)

Left in Heat mode and Right in the so called +8-15C Heat

**Comment by donnib** [comment]
![image](https://user-images.githubusercontent.com/252702/72807511-db763580-3c57-11ea-8717-7a6316019bca.png)
Left normal Heat mode - Right the so called +8-15C Heat mode

**Comment by lostfields** [comment]
okey, so if you set the temperature to 5 or 10 it enables the +8-15C heat mode?

**Comment by donnib** [comment]
Yup

**Comment by lostfields** [comment]
great, I think it's easier to let "management software" to support this special mode by setting temperature to 5/10 instead of having an extra mode as I can't find any flag that says the unit supports this.

Though, maybe all Panasonic unit supports +5-15C Heat mode.

**Comment by donnib** [comment]
Yes i agree.
