### ISSUE TITLE
deviceIdList error in session.py

### ISSUE THREAD

**Issue by austserve** [lostfields/python-panasonic-comfort-cloud#30]
I have not made any change or had any updated recently that I'm aware of, but as of today I get this error when running the pcomfortcloud.py script. I'm using 0.0.15 with openhab2.  This is the error I'm getting.

```
Traceback (most recent call last):
  File "/etc/openhab2/scripts/airconditioner.py", line 101, in <module>
    devices = session.get_devices()
  File "/usr/local/lib/python3.6/dist-packages/pcomfortcloud/session.py", line 177, in get_devices
    for device in group['deviceIdList']:
KeyError: 'deviceIdList'
```
Looking at the Panasonic app (Android) itself they have listed an update to add support for CZ-RTC6BLW (Remote Controller) as the Android app will not login either without being updated.

**Comment by arkadicolson** [comment]
I'm having the same problem...

**Comment by lostfields** [comment]
Panasonic has changed their JSON model, but should be fixed now at https://pypi.org/project/pcomfortcloud/0.0.16/

**Comment by austserve** [comment]
You're a legend. Fixed! Thank you for your efforts :-)
