### ISSUE TITLE
KeyError: deviceIdList

### ISSUE THREAD

**Issue by mriice** [lostfields/python-panasonic-comfort-cloud#31]
I've been using this amazing library for a while now, massive thanks for creating this! This morning it stopped working though and I'm seeing this in the logs every time I run it:

    line 6, in <module>
    devices = session.get_devices()
    File "/usr/local/lib/python2.7/dist-packages/pcomfortcloud/session.py", line 177, in get_devices
    for device in group['deviceIdList']:
    KeyError: 'deviceIdList'

The actual app seems to work fine (for once) so I don't think it's an issue with the API not being available. Is it possible the API has changed? Am I the only one seeing this?

Many thanks - Martin

**Comment by lostfields** [comment]
Hi, it should be solved in #30 in version 0.0.16 and I will keep this ticket open for a while to let others see as well.

**Comment by mriice** [comment]
Legend, thank you very much. Fixed.

**Comment by SeraphimSerapis** [comment]
I can confirm this works at least for https://github.com/djbulsink/panasonic_ac/ - thanks for the quick fix, @lostfields
