### ISSUE TITLE
Wrong deviceGuid encoding (new mainboard)

### ISSUE THREAD

**Issue by michelcve** [lostfields/python-panasonic-comfort-cloud#32]
I noticed a problem in deviceGuid encoding when using Panasonic_CC with HomeAssistant [https://github.com/sockless-coding/panasonic_cc/issues/12]. As the python-panasonic-comfort-cloud library seems to be used, I'm reporting my findings here as well.

I installed PCAP Remote, and captured some traffic while using the Panasonic App.

I noticed the ID of the new mainboard is somewhat different:

CS-A76C2097/20200210/M100007#

(I altered a few number, as to not publicly post my device guid, but please note that this GUID differs quite a lot from the standard 'devicetype-serialnumber').

When retrieving the deviceStatus the following URL is called:

GET /deviceStatus/now/CS-A76C2097f20200210fM100007%23

Which is a bit weird, seems like the '/' is encoded as a single 'f'. The '#' is encoded as '%23', which seems like normal URL encoding.

Could it be the strange '/' encoding, that causes the URL to be incorrect in panasonic_cc, resulting in the 404 that I'm seeing?

I'm happy to help if you need more information on this. Thanks for your help!

**Comment by lostfields** [comment]
Hi, the forward slash `/` id a bad thing to have in urls, the trafic you have captured is from this library?

**Comment by michelcve** [comment]
@lostfields I agree, but the traffic I captured is from the official Panasonic Comfort Cloud app. And I can't influence the guid/id

**Comment by lostfields** [comment]
I am guessing this library is using `%2f` instead of `f` and that is what causing the problem. I can make a modification and let you use that.

Do you python etc so we can try it out?

**Comment by michelcve** [comment]
@lostfields I'm not a python expert, but with some help I'll manage ;-)

**Comment by michelcve** [comment]
@lostfields I've just tried a few things. If I change the 'guid' in 'urls.py' to the following:

`guid.replace('/', 'f').replace('#', '%23')`

it seems to work (it now recognises the device in home assistant)

Both replaces were necessary.

Now this is of course not a 'clean' way to fix it, but you know python better then me ;-)

**Comment by lostfields** [comment]
Great, thanks. I will fix this

**Comment by michelcve** [comment]
@lostfields There is a slight problem with your fix. The quote_plus function translates the '/' to '%2F', so the replace should actually be ".replace('%2F', 'f')" for it to work properly.

**Comment by lostfields** [comment]
Hi, are you able to test [master](https://github.com/lostfields/python-panasonic-comfort-cloud) now?

**Comment by michelcve** [comment]
@lostfields I just applied the changes to my local installation, and they work properly. Thanks!

**Comment by lostfields** [comment]
great, I'll update the PyPi package as soon as possible.

**Comment by michelcve** [comment]
Thx!

**Comment by wdflorczyk** [comment]
Hi, do you know when will you be able to update the PyPi package. I use code, which depends on this and can't get this fixed.

**Comment by lostfields** [comment]
> Hi, do you know when will you be able to update the PyPi package. I use code, which depends on this and can't get this fixed.
Done :-) Version 0.0.18

**Comment by wdflorczyk** [comment]
Thank you!

**Comment by michelcve** [comment]
Thanks!
