### ISSUE TITLE
New version app has been published

### ISSUE THREAD

**Issue by richlock1** [lostfields/python-panasonic-comfort-cloud#35]
Hi,

Unfortunately there is also problem with accessing panasonic servers with the latest code for me.
Does anyone has the same problem?

Currently  this is the problem:

ricsi@ricsi-srv:~/Downloads/trees/pcomfort/python-panasonic-comfort-cloud$ ./pcomfortcloud.py <user> <pwd> list
Traceback (most recent call last):
  File "./pcomfortcloud.py", line 5, in <module>
    __main__.main()
  File "/home/ricsi/Downloads/trees/pcomfort/python-panasonic-comfort-cloud/pcomfortcloud/__main__.py", line 202, in main
    session.login()
  File "/home/ricsi/Downloads/trees/pcomfort/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/home/ricsi/Downloads/trees/pcomfort/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"message":"New version app has been published","code":4106}

Thanks to check.

**Comment by mortenf** [comment]
Same here, since a few hours ago.

**Comment by mortenf** [comment]
Apparently, some version check logic changed on the Panasonic side.

A quick fix: Change the app version number in session.py, for the HTTP header X-APP-VERSION, from 2.00 to 1.9.0 (which is the current version of the PCC app in app stores).

**Comment by richlock1** [comment]
> Apparently, some version check logic changed on the Panasonic side.
> 
> A quick fix: Change the app version number in session.py, for the HTTP header X-APP-VERSION, from 2.00 to 1.9.0 (which is the current version of the PCC app in app stores).

Very cool. The quick fix works for me also. Thanks the fast, great help :)

**Comment by lostfields** [comment]
Great, thanks, wish I had seen this before I started to sniff my phone :-D

**Comment by richlock1** [comment]
> Great, thanks, wish I had seen this before I started to sniff my phone :-D

Which app do you use for sniffing pcomfort cloud app? I might help in future with similar problems.

**Comment by lostfields** [comment]
well, I'm only using proxy at my phone to route all the traffic through Fiddler at my computer. This works as long the app itself doesn't do a certificate verification of issuer/domain.
