### ISSUE TITLE
New app again.

### ISSUE THREAD

**Issue by wdflorczyk** [lostfields/python-panasonic-comfort-cloud#38]
Hi. It looks this problem came back. 

WF
![Screenshot_20210121-091248_Home Assistant](https://user-images.githubusercontent.com/61596455/105322499-42ab2a80-5bc9-11eb-81e9-638ca97a380f.jpg)

**Comment by wdflorczyk** [comment]
Ok. There is an update to panasonic app on android.

**Comment by cigas4** [comment]
Any plans to add Aquarea smart cloud together? It uses same Panasonic comfort cloud smartphone app, but does not work on this integration.

**Comment by lostfields** [comment]
@cigas4 please create a new topic for that - I need help though, since I don't have the unit my self
