### ISSUE TITLE
403 Errors

### ISSUE THREAD

**Issue by craigtsmith** [lostfields/python-panasonic-comfort-cloud#40]
Hey, I use https://github.com/sockless-coding/panasonic_cc and noticed this project is listed is a dependency, I've just started getting  errors in HomeAssistant (the repo I use is a Home Assistant plugin) that relate to getting a 403 during obtaining a session.

I tested the mobile app and their services appear fine so must assume it's something related to previous issues mentioned here: https://github.com/sockless-coding/panasonic_cc/issues/17, here: #39 and here: #33.

I notice in previous reports it's something to do with an API version being updated, how can I discover if this is the case? I see nothing in the Mobile App about which version that is using?

Sorry I can't be of more help or offer a pull request - if I know how to determine the API version used in their mobile app I could probably put together a pull request.

**Comment by craigtsmith** [comment]
I connected my mobile to a proxy and noticed that `X-APP-VERSION` is now `1.10.1` I will prepare a PR to fix this shortly

**Comment by lostfields** [comment]
This is a pain in the ***  but app-version `1.10.0` works for me, still...  I was thinking we had to make a version routine that patches itself, but I tried version `1.20.0` and even `2.10.0` and all of them works. If we up the version-number a lot more than 1 minor or patch it will work a longer than keep following the app-version.

is that working for you?

**Comment by LudovicRousseau** [comment]
On my side I have no problem with the current python-panasonic-comfort-cloud code.
It is still working fine, no need to change the "X-APP-VERSION".

**Comment by craigtsmith** [comment]
I will test again this evening - perhaps I jumped the gun and my issues were unrelated to the `X-APP-VERSION` header

**Comment by craigtsmith** [comment]
Hey - sorry for delay, busy week. 
I have just re-tested and got the same issue, so uninstalled the library that was using `python-panasonic-comfort-cloud` and reinstalled it and that resolved the issue, so can only assume it was some local issue. Apologies for that! 

I'll close this issue + the PR now.
