### ISSUE TITLE
Weird problems

### ISSUE THREAD

**Issue by MatthK** [lostfields/python-panasonic-comfort-cloud#42]
I have created a php based webpage to control my A/C based on your solution here. It used to work just fine but since a few days, I keep getting timeouts and strange values back. If the login works, values reported back don't correspond to actual status.

The strange thing is sometimes I do get a reply, sometimes I just receive a "none", while most of the times I get a timeout.

Are there some changes on the cloud or is that a problem with my setup?

**Comment by LudovicRousseau** [comment]
I also get different errors at different times from the server since yesterday.
It looks like the Panasonic cloud service is not in a good shape.
