### ISSUE TITLE
Suggestions for not getting 403

### ISSUE THREAD

**Issue by techbliss** [lostfields/python-panasonic-comfort-cloud#47]
Hello i found this great repo via [hjemmeautomasjon.no/](https://www.hjemmeautomasjon.no/forums/topic/4101-panasonic-comfort-cloud-integrasjon/?page=2)
I got a fibaro homecenter 3, but that uses Lua Language, and trying to use some of your code to try control my aircon via fibaro.

first thing todo was to get a 200 repsonse when logging into panasonic cloud, but i get an 403 no matter what i did in Lua, so i then tried a minimalistic python script to test , but also there i get 403
.
```import requests, json
import os
import requests
import json
from json import *
cafile= os.path.join(os.path.dirname(__file__),
                    "certificatechain.pem")
sert = 'C:\\AMD\\certificatechain.pem'
print cafile
URL = 'https://accsmart.panasonic.com/auth/login/'
PARAMS = {
    "language": '1',
    "password": '*****',
    "loginId": '******* }
inputheaders = {
    "X-APP-TYPE": "1",
    "X-APP-VERSION": "1.10.0",
    "Accept": "application/json",
    "Content-Type": "application/json",
    "SERVER_PROTOCOL": "HTTP/1.1"
    }

r = requests.post(URL, params=PARAMS,
                  headers= inputheaders, verify=sert)
print PARAMS
# extracting data in json format
data = r.status_code
print(data)
```

Any suggestions for a minimalistic login.
Keep up the good work.

**Comment by lostfields** [comment]
Try to add user-agent
https://github.com/lostfields/python-panasonic-comfort-cloud/blob/f3975e4070abe1bd959dda6d51571f568de7d592/requests.http#L25

**Comment by techbliss** [comment]
i put the user agent G roc in , then i got a response 400 back.
after reading [python requests POST 400 error](https://stackoverflow.com/a/55346668)
i then change json instead of data.

i get a 200 reponse

```inputheaders = {
    "X-APP-TYPE": "1",
    "X-APP-VERSION": "1.10.0",
   # "X-User-Authorization": "ABn5iAlFvmDjRmIe1BWZ6iMSc48T0nul",

    "User-Agent": "G-RAC",
    "Accept": "application/json",
    "Content-Type": "application/json",
    "SERVER_PROTOCOL": "HTTP/1.1"
    }

# sending get request and saving the response as response object
r = requests.post(URL, json=PARAMS,
                  headers= inputheaders, verify=sert, )
````
output
````200
{"uToken":"**********************z4egHuz0KpxM","result":0,"language":14}

Process finished with exit code 0
``````
i guess the next step is to use the Token
