### ISSUE TITLE
They updated app

### ISSUE THREAD

**Issue by techbliss** [lostfields/python-panasonic-comfort-cloud#49]
https://github.com/lostfields/python-panasonic-comfort-cloud/blob/f3975e4070abe1bd959dda6d51571f568de7d592/pcomfortcloud/session.py#L111

new version is working with 
        ['X-APP-VERSION'] = '1.12.0',

**Comment by TomS1985** [comment]
Is it possible to get the latest version of the app automatically from the google play store website ( https://play.google.com/store/apps/details?id=com.panasonic.ACCsmart&hl=en&gl=US ) of the app? There is displayed the latest version of the app.

**Comment by sockless-coding** [comment]
@TomS1985 Google does unfortunately not provide an API to get the latest version of a published app, but Apple does, so I've created a pull request that enabled automatic version detection.

**Comment by techbliss** [comment]
Thx
issue closed
