### ISSUE TITLE
Error: "New version app has been published"

### ISSUE THREAD

**Issue by michelcve** [lostfields/python-panasonic-comfort-cloud#51]
As of today I'm receiving errors "New version app has been published".

I presume you need to update the X-APP-VERSION string again, just like you did in https://github.com/lostfields/python-panasonic-comfort-cloud/issues/7

**Comment by michelcve** [comment]
Setting it to 1.12.0 in session.py will solve it (same version as current app).

**Comment by sockless-coding** [comment]
I've created a more permanent solution for this issue with #50

**Comment by michelcve** [comment]
That's great, will close this one. Thanks!
