### ISSUE TITLE
Version changed again

### ISSUE THREAD

**Issue by nelsongraca** [lostfields/python-panasonic-comfort-cloud#62]
I use this library because it is a dependency of [this HA integration](https://github.com/sockless-coding/panasonic_cc) today my ACs stopped working, I ended up finding that the version has changed to "1.15.0" could we have it updated?

Is there any chance [this](https://github.com/lostfields/python-panasonic-comfort-cloud/pulls) will be merged/improved to be merged?

**Comment by HKGEric** [comment]
same issue

**Comment by Th0masDB** [comment]
I made a pull request #63
