### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by mdickert** [lostfields/python-panasonic-comfort-cloud#64]
Hi, 
I use the script in a Linux shell. Since today I get the following error code:

````
Traceback (most recent call last):
  File "/home/iobroker/Panasonic/python-panasonic-comfort-cloud/pcomfortcloud.py", line 5, in <module>
    __main__.main()
  File "/home/iobroker/Panasonic/python-panasonic-comfort-cloud/pcomfortcloud/__main__.py", line 202, in main
    session.login()
  File "/home/iobroker/Panasonic/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/home/iobroker/Panasonic/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
```
`
On Android I saw that the 1st request of the Panasonic App includes an "deviceId" could this the reason?

            "clientId": "DYkT1gzGpfG5l9XXXQ8li16K0DTHTXXX", 
            "language": "0", 
            "loginId": self._username, 
            "password": self._password

**Comment by butterdn** [comment]
Me too, just happen today

**Comment by BVGorp** [comment]
same issue as #62

**Comment by FrankVanSeggelen** [comment]
I have exact same problem, after changing 1.20 to 1.50 still the same issue

**Comment by slvwolf** [comment]
Seems none of the versions `1.15.0`, `1.20.0` or `1.50.0` work anymore

**Comment by nelsongraca** [comment]
@slvwolf can confirm

**Comment by slvwolf** [comment]
Everything works again after adding the `charset=utf-8` changes mentioned in #63 and updating version to `1.15.1`.

``` python
    def _headers(self):
        return {
            "X-APP-TYPE": "1",
            "X-APP-VERSION": "1.15.1",
            "X-User-Authorization": self._vid,
            "User-Agent": "G-RAC",
            "Accept": "application/json; charset=utf-8",
            "Content-Type": "application/json; charset=utf-8"
        }
```

**Comment by krism23** [comment]
> Everything works again after adding the `charset=utf-8` changes mentioned in #63 and updating version to `1.15.1`.
> 
> ```python
>     def _headers(self):
>         return {
>             "X-APP-TYPE": "1",
>             "X-APP-VERSION": "1.15.1",
>             "X-User-Authorization": self._vid,
>             "User-Agent": "G-RAC",
>             "Accept": "application/json; charset=utf-8",
>             "Content-Type": "application/json; charset=utf-8"
>         }
> ```

Made the change via docker (running supervisor) but no luck

**Comment by wmmudde** [comment]
> Everything works again after adding the `charset=utf-8` changes mentioned in #63 and updating version to `1.15.1`.
> 
> ```python
>     def _headers(self):
>         return {
>             "X-APP-TYPE": "1",
>             "X-APP-VERSION": "1.15.1",
>             "X-User-Authorization": self._vid,
>             "User-Agent": "G-RAC",
>             "Accept": "application/json; charset=utf-8",
>             "Content-Type": "application/json; charset=utf-8"
>         }
> ```

Hi,

where did you put this?
Which file do I need to edit to make it work again?

**Comment by slvwolf** [comment]
Re-verified the new headers again this morning and everything seems to be working fine. Alternative workaround for this issue is to utilise a simple wrapper until the issue is solved on the library side, 

```
class SessionWrapper(pcomfortcloud.Session):
    """
    Wrapper for changing the version string in session 
    """
    def _headers(self):
        return {
            "X-APP-TYPE": "1",
            "X-APP-VERSION": "1.15.1",
            "X-User-Authorization": self._vid,
            "User-Agent": "G-RAC",
            "Accept": "application/json; charset=utf-8",
            "Content-Type": "application/json; charset=utf-8"
        }

session = SessionWrapper(username, password)
```
(example: https://github.com/slvwolf/panasonic-comfort-cloud-mqtt/blob/main/pcfmqtt/service.py#L10)

**Comment by wmmudde** [comment]
> Re-verified the new headers again this morning and everything seems to be working fine. Alternative workaround for this issue is to utilise a simple wrapper until the issue is solved on the library side,
> 
> ```python
> class SessionWrapper(pcomfortcloud.Session):
>     """
>     Wrapper for changing the version string in session 
>     """
>     def _headers(self):
>         return {
>             "X-APP-TYPE": "1",
>             "X-APP-VERSION": "1.15.1",
>             "X-User-Authorization": self._vid,
>             "User-Agent": "G-RAC",
>             "Accept": "application/json; charset=utf-8",
>             "Content-Type": "application/json; charset=utf-8"
>         }
> 
> session = SessionWrapper(username, password)
> ```
> 
> (example: https://github.com/slvwolf/panasonic-comfort-cloud-mqtt/blob/main/pcfmqtt/service.py#L10)

Is it possible to share your panasonic_cc folder so I can make it work?

**Comment by timovp** [comment]
> > Everything works again after adding the `charset=utf-8` changes mentioned in #63 and updating version to `1.15.1`.
> > ```python
> >     def _headers(self):
> >         return {
> >             "X-APP-TYPE": "1",
> >             "X-APP-VERSION": "1.15.1",
> >             "X-User-Authorization": self._vid,
> >             "User-Agent": "G-RAC",
> >             "Accept": "application/json; charset=utf-8",
> >             "Content-Type": "application/json; charset=utf-8"
> >         }
> > ```
> 
> Hi,
> 
> where did you put this? Which file do I need to edit to make it work again?



> Everything works again after adding the `charset=utf-8` changes mentioned in #63 and updating version to `1.15.1`.
> 
> ```python
>     def _headers(self):
>         return {
>             "X-APP-TYPE": "1",
>             "X-APP-VERSION": "1.15.1",
>             "X-User-Authorization": self._vid,
>             "User-Agent": "G-RAC",
>             "Accept": "application/json; charset=utf-8",
>             "Content-Type": "application/json; charset=utf-8"
>         }
> ```

Can confirm, this worked for me as wel :-)

**Comment by lostfields** [comment]
I'll look into this, and will merge the changes to master very soon. Thanks for finding out all of this
