### ISSUE TITLE
token creation error

### ISSUE THREAD

**Issue by thxraph** [lostfields/python-panasonic-comfort-cloud#74]
Hey guys, i'm having this one....
login/pass are correct, version is .23 (last)

File "/usr/local/lib/python3.9/dist-packages/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/usr/local/lib/python3.9/dist-packages/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data:

everything was working alright....any Q?
Thank you

**Comment by lostfields** [comment]
Hmm, status code is for throttle, way too many requests

**Comment by thxraph** [comment]
correct, I stopped making requests for 12h, and everything is back to normal! thank you very much!
