### ISSUE TITLE
Try to send request via postman

### ISSUE THREAD

**Issue by LuckyLukeG** [lostfields/python-panasonic-comfort-cloud#76]
For my homematic IP homeautomatisation i looking to get the informations of my aitcoditions from panasonic comfort cloud.
I try to simulate the necessary commands like your requests with app postman with my account data of comfort cloud, but for login i get only response "403 Forbidden".
Do you have an idea what going wrong?

**Comment by lostfields** [comment]
Take a look at the samples at https://github.com/lostfields/python-panasonic-comfort-cloud/blob/master/requests.http 
You may have to add new headers as described at https://github.com/lostfields/python-panasonic-comfort-cloud/blob/8e40ae217261ef4a49deaa3df14f64af7f698bb1/pcomfortcloud/session.py#L113-L115
