### ISSUE TITLE
Invalid response, status code: 400

### ISSUE THREAD

**Issue by majurgens** [lostfields/python-panasonic-comfort-cloud#78]
The Panasonic cloud was down for several hours today (even their app was not working) and now that it is back up I am getting the following error when trying to connect. Presumably there has been some kind of upgrade/protocol change

```
Traceback (most recent call last):
  File "/tmp/python-panasonic-comfort-cloud/pcomfortcloud.py", line 5, in <module>
    __main__.main()
  File "/tmp/python-panasonic-comfort-cloud/pcomfortcloud/__main__.py", line 202, in main
    session.login()
  File "/tmp/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/tmp/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 400 - Data: {"code":"4000"，"message":"Missing required header parameter or bad request for header"}
```

**Comment by mcbrain78** [comment]
Same here, tried to override the header version with 19.1, 19.2, 20 and it didn't help

**Comment by mlpplm** [comment]
Same here. With "X-APP-VERSION: 1.17.0" the response is: {"code":"4106", "message": "New version app has been published"} and with "X-APP-VERSION: 1.18.0" {"code":"4000"，"message":"Missing required header parameter or bad request for header"}. Thus, this time they must have changed the required headers and just finding a new version number won't work (i.e. 1.18.0 is probably still the right one).

**Comment by marc2016** [comment]
The REST call needs some additional headers:
`X-APP-TYPE:1
X-APP-VERSION:1.18.0
Accept:application/json; charset=utf-8
Content-Type:application/json
User-Agent:G-RAC
X-APP-TIMESTAMP:1
X-APP-NAME:Comfort Cloud
X-CFC-API-KEY:Comfort Cloud`
The last three are new for me.

**Comment by LudovicRousseau** [comment]
I had to accept a new confidentiality policy on the iPhone application. But that does not solve the problem. I still have the same error:
```
pcomfortcloud.session.ResponseError: Invalid response, status code: 400 - Data: {"code":"4000"，"message":"Missing required header parameter or bad request for header"}
```

But thanks to @marc2016 it now works for me with this patch:
```patch
diff --git a/pcomfortcloud/session.py b/pcomfortcloud/session.py
index bf9f6a5..cb15ec0 100644
--- a/pcomfortcloud/session.py
+++ b/pcomfortcloud/session.py
@@ -110,6 +110,9 @@ class Session(object):
             "X-APP-TYPE": "1",
             "X-APP-VERSION": "1.19.0",
             "X-User-Authorization": self._vid,
+            "X-APP-TIMESTAMP": "1",
+            "X-APP-NAME": "Comfort Cloud",
+            "X-CFC-API-KEY": "Comfort Cloud",
             "User-Agent": "G-RAC",
             "Accept": "application/json; charset=utf-8",
             "Content-Type": "application/json; charset=utf-8"
```

**Comment by MatthK** [comment]
Awesome, that fixed it for me too.

How do you guys find that out? That is just really cool.

**Comment by ivx675** [comment]
Seems https://accsmart.panasonic.com/deviceHistoryData has more than these header changes.
I got status and device control working, but can't read out power consumption. 
It still gives 400 error with new headers.
Does anybody use deviceHistoryData ?

**Comment by atchoo78** [comment]
> Also looking for a solution :|
> 
> I'm getting a `{"code":"4100","message":"Token expires"}` reply. But the login doesn't work.
> 
> Edit: After some more fiddling, I now get a null reply. And this is a curl log:

@MatthK  I'm getting that error message all over the place suddenly. Do you remember any of that fiddling you did to fix it? 🤤

**Comment by MatthK** [comment]
I think it was adjusting the headers.

But I'm not using this anymore since the login procedure got changed some time ago.
