### ISSUE TITLE
Error: New version app has been published

### ISSUE THREAD

**Issue by majurgens** [lostfields/python-panasonic-comfort-cloud#85]
Just started within the last few minutes for me when calling the API. I'm guessing something in the API has changed again.

```
Traceback (most recent call last):
  File "/opt/hvac/python-panasonic-comfort-cloud/pcomfortcloud.py", line 5, in <module>
    __main__.main()
  File "/opt/hvac/python-panasonic-comfort-cloud/pcomfortcloud/__main__.py", line 224, in main
    session.login()
  File "/opt/hvac/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/opt/hvac/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 135, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"code":"4106", "message": "New version app has been published"}
```

**Comment by Cheesekeeper** [comment]
Looks like the app has been updated again. You can get working by making the following change. In session.py find the following block:
def _headers(self):
        return {
            "X-APP-TYPE": "1",
            "X-APP-VERSION": "1.19.0",
            "X-User-Authorization": self._vid,
            "X-APP-TIMESTAMP": "1",
            "X-APP-NAME": "Comfort Cloud",
            "X-CFC-API-KEY": "Comfort Cloud",
            "User-Agent": "G-RAC",
            "Accept": "application/json; charset=utf-8",
            "Content-Type": "application/json; charset=utf-8"
        }

Change X_APP_VERSION to:
            "X-APP-VERSION": "1.20.0",

However when I did this on mine while it got rid of the version error, I got a new error on createtoken. If you get the same, look at the next block down from the one you just updated which looks like this:

        payload = {
            "language": "0",
            "loginId": self._username,
            "password": self._password
        }

Change the language setting to remove the double quotes around "0" like this:
            "language": 0,

After those 2 changes it worked for me.

**Comment by majurgens** [comment]
I confirm that this fixed it for me too. Thanks

**Comment by MetalOctopus** [comment]
@Cheesekeeper - I'm popping your solution into a different repository that's used for HomeAssistant integration. 
Thanks very much for your help here! 

Always a pain when the AC stops working on a 30 degree day 🥇

**Comment by jackalsdance** [comment]
Is this repo going to be updated to avoid the need for a workaround as its non trivial to do in Home Assistant....

**Comment by MetalOctopus** [comment]
@jackalsdance - I wrote a HACS guide here if it can help you.

https://github.com/djbulsink/panasonic_ac/issues/45

**Comment by jackalsdance** [comment]
Yup noted but that requires the setup of ssh to the HA core, which is annoying for me as I'm lazy and need to find a usb key etc, but for many is beyond their technical abilities I suspect....

**Comment by jackalsdance** [comment]
Thank you!
