### ISSUE TITLE
Question about historical hourly data

### ISSUE THREAD

**Issue by kiwicanbrett** [lostfields/python-panasonic-comfort-cloud#88]
Is the hourly historical data stored with UTC times, so that the tz offset parameter in the history method simply adds a constant offset for the date of interest. The question is really what happens on days when daylight savings starts or stops. Should I really just download with a time offset of "+0:00" and adjust for daylight savings times on my side.

**Comment by heldchen** [comment]
what hourly historical data are you refering to? where do you "download" this data?

**Comment by kiwicanbrett** [comment]
I use the history method of Session to download historical data. I've found the answer myself, best way is to download the historical data with a time zone offset of 0, and use the time-aware capabilities of the python datetime module to get to the correct times for a time zone of interest including DST adjustments.
